micronaut:
  application:
    name: locationReadV1
  server:
    port: 8080

---
cassandra:
  default:
    clusterName: '"myCluster"'
    contactPoint: '"localhost"'
    port: 9042
    maxSchemaAgreementWaitSeconds: 20
    ssl: false
